### ISSUE TITLE
Please Release Version: 5.2.0

### ISSUE THREAD

**Issue by msiemczyk** [webjars/pnotify#7]
Classic jar

**Comment by jamesward** [comment]
It looks like they don't really have a dist zip for everything anymore:
https://github.com/sciactive/pnotify/blob/master/README.md#getting-started

Consuming this via NPM WebJars would be a lot easier. Is there a reason that doesn't work for you?

**Comment by msiemczyk** [comment]
Yes, our software is built using Gradle and there is not good support to download NPM packages and build war with it, while with classic webjars is as simple as adding compile dependency.

dependencies {
    //compile 'org.webjars.npm:pnotify:5.2.0'
    compile 'org.webjars:chartjs:2.9.4'
    compile 'org.webjars:angular-chart.js:1.1.1'
}

**Comment by jamesward** [comment]
Oh! NPM WebJars are just regular Jars but based on the NPM package contents. So you don't need NPM. For example, you can use:
```
compile 'org.webjars.npm:pnotify__core:5.1.2'
```
The contents are:
https://www.webjars.org/listfiles/org.webjars.npm/pnotify__core/5.1.2

Note that `org.webjars.npm:pnotify:5.2.0` doesn't really have anything in it. It just has transitive dependencies on other packages: https://repo1.maven.org/maven2/org/webjars/npm/pnotify/5.2.0/pnotify-5.2.0.pom

**Comment by msiemczyk** [comment]
Ah, ok. I was confused by the "empty" pnotify npm package. I see now that I can just use individual npm packages:

![image](https://user-images.githubusercontent.com/5693250/109191709-6c291a00-7764-11eb-835d-7293d3d141ae.png)

Last question: I don't see 5.2.0 version of those packages, any ideas why? do we just need to release new version of those? There seems to be some 5.2.0 modules like bootstrap4 or confirm, but not the core and the ones I'm using.

**Comment by jamesward** [comment]
Cool.  It looks like no one has deployed those `5.2.0` version yet. You can do that via https://www.webjars.org

Let me know if you run into any issues.
